spring.application.name=library_management

jwt.secret=mysecretkeymysecretkeymysecretkey
jwt.expiration=86400000

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/librarydb}

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true
